import React from "react";
import Head from "next/head";
import { Navbar } from "../../components/shared/Navbar";
import { Footer } from "../../components/shared/Footer";

interface AcidProps {}

const Acid: React.FC<AcidProps> = ({}) => {
    return (
        <div>
            <Head>
                <title>89 Alkaline - Acid is your worst enemy</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="mx-auto max-w-4xl p-7 itc">
                <img
                    style={{ height: "40vh" }}
                    className="mx-auto w-auto"
                    src="https://i.ibb.co/vPVw06v/junk-food-1.png"
                />
                <h1 className="text-center text-blue text-3xl md:text-4xl md:font-bold mb-6">
                    Acidification – Your Body’s Worst Enemy!
                </h1>
                <div className="mx-auto w-4/5 reg">
                    <p className="text-blue my-7">
                        Are you aware that an acidic body condition is the
                        underlying cause of many adult degenerative diseases
                        such as Cancer, Hypertension, High Blood Pressure,
                        Diabetes, Arteriosclerosis, Kidney problems, Gout,
                        Arthritis, Osteoporosis, Gastric Ulcers, Eczema,
                        Constipation, Stress and Fatigue, etc…? It also hastens
                        the Ageing Process.
                    </p>
                </div>
                <div className="text-blue w-4/5 mx-auto my-6">
                    <h1 className="text-2xl md:text-3xl md:font-bold mb-3">
                        What causes Acidification?
                    </h1>
                    <p className="reg">
                        Acidification is the accumulation of acidic wastes
                        within our bodies. Our daily food intake produces
                        “acids” in the process of digestion and absorption.
                        Environmental pollution, food additives, chemicals and
                        emotional stresses also contribute to acidification.
                    </p>
                </div>
                <div className="text-blue w-4/5 mx-auto my-6">
                    <h1 className="text-2xl md:text-3xl md:font-bold mb-3">
                        How can we correct acidification?
                    </h1>
                    <p className="reg">
                        Poor diets, either in the present or past, can cause
                        acidic wastes to be stored in the body. When acidic
                        wastes enter our bloodstream, the blood, in order to
                        maintain the narrow pH range, will store them in various
                        parts of the body. Acid salts stored in the body over
                        time will overburden the system and lead to various
                        degenerative diseases.
                    </p>
                </div>
                <p className="text-blue w-4/5 mx-auto my-6 reg">
                    Alkaline neutralizes the acid. Regular drinking of
                    89Alkaline Ionized Water of 8.9pH+ is ionized with
                    platinum-dipped titanium plates is an antioxidant that helps
                    to neutralize harmful stored acidic wastes and eliminate
                    them harmlessly from the body.
                </p>
            </div>
            <Footer />
        </div>
    );
};

export default Acid;
