import React from "react";
import { Footer } from "../components/shared/Footer";
import { Navbar } from "../components/shared/Navbar";
import Head from "next/head";

interface AboutProps {}

const About: React.FC<AboutProps> = ({}) => {
    return (
        <div>
            <Head>
                <title>89 Alkaline - About</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="mx-auto max-w-4xl p-7 itc">
                <h1 className="text-center text-blue text-5xl font-bold mb-6">
                    Health benefits of Alkaline water
                </h1>
                <div className="flex mb-8">
                    <div className="w-1/5">
                        <img className="w-96 h-auto" src="img/ph.jpg" />
                    </div>
                    <div className="w-4/5">
                        <h1 className="text-blue text-2xl font-bold mb-2">
                            A Balanced 8.9pH - A Key to Healthy Living
                        </h1>
                        <p className="text-blue">
                            The human body tends to maintain body fluid at pH
                            7.35 according to the homeostasis function. It tries
                            to maintain the balance of each organ with alkaline
                            body fluid of pH 8.8 from the pancreas as the peak.
                            However, a consistent acidic condition will result
                            in lowering one{"'"}s immune system. Ionized
                            alkaline water with pH 8.5-9.5 is best suitable to
                            counter the harmful effects of build-up of acidic
                            wastes.
                        </p>
                    </div>
                </div>
                <div className="flex mb-8">
                    <div className="w-1/5">
                        <img
                            className="w-96 h-auto"
                            src="img/antioxidants.jpg"
                        />
                    </div>
                    <div className="w-4/5">
                        <h1 className="text-blue text-2xl font-bold mb-2">
                            Abundant Antioxidants - Combats Free Radicals
                        </h1>
                        <p className="text-blue">
                            A high or rising positive ORP (+ORP) causes
                            oxidation that in turn causes ageing. The -ORP from
                            an ionizer is effective in counteracting this
                            process. Ionized Alkaline water renews our bodies at
                            the cellular level. This is as close as it gets to
                            reach the Fountain of Youth!
                        </p>
                    </div>
                </div>
                <div className="flex mb-8">
                    <div className="w-1/5">
                        <img className="w-96 h-auto" src="img/hydrogen.jpg" />
                    </div>
                    <div className="w-4/5">
                        <h1 className="text-blue text-2xl font-bold mb-2">
                            Easily Utilised Antioxidants
                        </h1>
                        <p className="text-blue">
                            Another key driving force of the antioxidants in
                            Ionized Alkaline water is the rich presence of
                            activated hydrogen which is easily absorbed into the
                            body to counter free radicals, unstable hydroxyl
                            radicals which cause damage to the body cells and
                            convert them into water to be easily disposed of.
                            This helps to boost immunity.
                        </p>
                    </div>
                </div>
                <div className="flex mb-8">
                    <div className="w-1/5">
                        <img className="w-96 h-auto" src="img/minerals.jpg" />
                    </div>
                    <div className="w-4/5">
                        <h1 className="text-blue text-2xl font-bold mb-2">
                            Alkaline Ionized Minerals (Ca2+) - Restoring
                            Minerals
                        </h1>
                        <p className="text-blue">
                            Ionized Alkaline water gives you minerals in ionized
                            form that are easily assimilated into the body.
                            These ionized minerals are not only good for
                            building strong bones and teeth, but they are also
                            vital in providing the alkaline pH of the water to
                            help our bodies counter the acid wastes buildup.
                        </p>
                    </div>
                </div>
                <div className="flex mb-8">
                    <div className="w-1/5">
                        <img className="w-96 h-auto" src="img/dna.jpg" />
                    </div>
                    <div className="w-4/5">
                        <h1 className="text-blue text-2xl font-bold mb-2">
                            Smaller Water Clusters - Microcluster and Hexagonal
                            Effect
                        </h1>
                        <p className="text-blue">
                            Ionized Alkaline water molecule clusters are smaller
                            than other types of water. It is this smaller size
                            that helps to hydrate cells more efficiently.
                            Additionally, the use of Ionized Alkaline water is
                            great in food and beverage preparation because it
                            helps dishes and drinks to taste more flavorful and
                            decreases the rate of decay!
                        </p>
                    </div>
                </div>
                <div className="flex mb-8">
                    <div className="w-1/5">
                        <img className="w-96 h-auto" src="img/body-clean.jpg" />
                    </div>
                    <div className="w-4/5">
                        <h1 className="text-blue text-2xl font-bold mb-2">
                            Accelerated Detoxification - Keeping the Body Clean!
                        </h1>
                        <p className="text-blue">
                            One of the functions of water is the removal of
                            waste and toxics, which Ionized Alkaline water helps
                            with quickly. With its smaller water clusters and
                            the ability of hydrogen to neutralise hydroxyl
                            radicals into water, this becomes a great transport
                            system in excreting waste matter from the body
                            rapidly. This helps the body to detoxify and
                            provides for better hydration.
                        </p>
                    </div>
                </div>
                <div className="flex mb-8">
                    <div className="w-1/5">
                        <img className="w-96 h-auto" src="img/water.jpg" />
                    </div>
                    <div className="w-4/5">
                        <h1 className="text-blue text-2xl font-bold mb-2">
                            Reducing Wrinkles, Growing Suppleness!
                        </h1>
                        <p className="text-blue">
                            Alkaline water has been tested and proven to be able
                            to stimulate type 1 collagen production which helps
                            to reduce wrinkles and enables more supple and
                            radiant skin when Ionized Alkaline water is directly
                            applied to it!
                        </p>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default About;
