import React from "react";
import Head from "next/head";
import { Navbar } from "../components/shared/Navbar";
import { Footer } from "../components/shared/Footer";

interface contactProps {}

const Contact: React.FC<contactProps> = ({}) => {
    return (
        <div>
            <Head>
                <title>Contact | 89 Alkaline</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="max-w-xl mx-3 md:mx-auto my-10">
                <h1 className="text-blue itc text-5xl">Contact Us</h1>
                <hr className="bt bt-gray-500 my-4" />
                <div className="mb-5">
                    <p className="text-blue itc tracking-small text-sm mb-0.5">
                        FIRST NAME
                    </p>
                    <input
                        className="w-full py-1.5 px-2 text-sm border border-blue focus:outline-none rounded-sm"
                        placeholder="First name"
                    />
                </div>
                <div className="mb-5">
                    <p className="text-blue itc tracking-small text-sm mb-0.5">
                        LAST NAME
                    </p>
                    <input
                        className="w-full py-1.5 px-2 text-sm border border-blue focus:outline-none rounded-sm"
                        placeholder="Last name"
                    />
                </div>
                <div className="mb-5">
                    <p className="text-blue itc tracking-small text-sm mb-0.5">
                        EMAIL
                    </p>
                    <input
                        className="w-full py-1.5 px-2 text-sm border border-blue focus:outline-none rounded-sm"
                        placeholder="Email name"
                    />
                </div>
                <div className="mb-5">
                    <p className="text-blue itc tracking-small text-sm mb-0.5">
                        PHONE
                    </p>
                    <input
                        className="w-full py-1.5 px-2 text-sm border border-blue focus:outline-none rounded-sm"
                        placeholder="Phone"
                    />
                </div>
                <div className="mb-5">
                    <p className="text-blue itc tracking-small text-sm mb-0.5">
                        COMPANY
                    </p>
                    <input
                        className="w-full py-1.5 px-2 text-sm border border-blue focus:outline-none rounded-sm"
                        placeholder="Company"
                    />
                </div>
                <div className="mb-5">
                    <p className="text-blue itc tracking-small text-sm mb-0.5">
                        ALREADY A CUSTOMER?
                    </p>
                    <select className=" w-full border border-blue rounded-sm py-2 px-2 text-blue text-sm itc tracking-small uppercase focus:outline-none">
                        <option value="yes">Yes</option>
                        <option value="yes">No</option>
                    </select>
                </div>
                <div className="mb-5">
                    <p className="text-blue itc tracking-small text-sm mb-0.5">
                        COMMENTS
                    </p>
                    <textarea
                        style={{ minHeight: "40px" }}
                        className="w-full py-1.5 px-2 text-sm border border-blue focus:outline-none rounded-sm"
                        placeholder="Comments"
                    />
                </div>
                <button
                    style={{ fontSize: "12px" }}
                    className="w-full bg-blue py-2.5 px-5 itc tracking-small uppercase text-white"
                >
                    SUBMIT
                </button>
            </div>
            <Footer />
        </div>
    );
};

export default Contact;
