import React from "react";
import Head from "next/head";
import { Navbar } from "../components/shared/Navbar";
import { Footer } from "../components/shared/Footer";

interface DoctorsProps {}

const Doctors: React.FC<DoctorsProps> = ({}) => {
    return (
        <div>
            <Head>
                <title>89 Alkaline - What doctors say</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="mx-auto max-w-4xl p-7 itc">
                <h1 className="text-center text-blue text-4xl md:text-5xl md:font-bold mb-6">
                    What doctors say
                </h1>
                <div className="mx-auto w-4/5 reg my-6">
                    <h1 className="text-blue reg text-2xl md:text-3xl md:font-bold mb-2">
                        Heart Disease
                    </h1>
                    <p className="text-blue mb-7">
                        In my opinion, the wonder of ionized water is the
                        ability neutralizes toxins, but it is not a medicine.
                        The difference is that the medicine can only apply to
                        each and individual case. whereas the ionized water can
                        be consumed generally and its neutralizing power is
                        something which is very much unexpected. Now, in brief,
                        let me introduce to you a heart disease case and how it
                        was cured.
                    </p>
                    <p className="text-blue my-7">
                        The patient was a 35 years old male suffering from
                        vascular heart disease. For 5 years, his sickness
                        deteriorated. He was in the Setagays Government Hospital
                        for treatment.
                    </p>
                    <p className="text-blue my-7">
                        During those 5 years, he had been in and out of the
                        hospital 5 to 6 times. He had undergone high tech
                        examinations such as angiogram by injecting VINYL via
                        the vein into the heart. He consulted and sought
                        treatment from many good doctors where later he
                        underwent a major surgical operation. upon his discharge
                        from the hospital, he quit his job to convalesce.
                        However, each time when his illness relapsed, the attack
                        seemed to be even more severe. Last year, in August, his
                        relatives were in despair and expected he would not live
                        much longer. It so happened at that time that the victim
                        {"’"}s relative came across ionized water processor. His
                        illness responded well and he is now on the road to
                        recovery.”
                    </p>
                    <p className="text-blue my-7">
                        Note: In the United States, cardiovascular diseases
                        account for more than one-half of the approximate 2
                        million deaths occurring each year. It is estimated that
                        optimal conditioning of drinking water could reduce this
                        cardiovascular disease mortality rate by as much as 15
                        percent in the United States.
                    </p>
                    <p className="intr text-brown font-medium">
                        - Prof. Kuwata Keijiroo, Doctor of Medicine, Japan
                    </p>
                </div>
                <hr className="border-b bg-gray-300" />
                <div className="mx-auto w-4/5 reg my-6">
                    <h1 className="text-blue reg text-2xl md:text-3xl md:font-bold mb-2">
                        High Blood Pressure
                    </h1>
                    <p className="text-blue mb-7">
                        For over 10 years of my experience, my concept toward
                        minerals, especially pertaining to ionic calcium in high
                        blood pressure and other diseases is most significant.
                    </p>
                    <p className="text-blue my-7">
                        In accordance to the theory of medical Professor Gato of
                        Kyushu University on Vitamin K (because vitamin K
                        enables the blood calcium to increase), or the
                        consumption of more ionized water , the effectiveness of
                        the increase in the calcium in high blood pressure is
                        most significant. Too many fats in the diets, which lead
                        to the deposition of cholesterol on the blood vessels,
                        which in turn constrict the blood flow, cause most
                        illnesses such as high blood pressure.
                    </p>
                    <p className="text-blue my-7">
                        By drinking ionized water for a period of 2 to 3 months,
                        the blood pressure should slowly drop, because the
                        ionized water is a good solvent, which dissolves the
                        cholesterol in the blood vessels.”
                    </p>
                    <p className="intr text-brown font-medium">
                        - Prof. Kuninaka Hironage, Head of Kuninaka Hospital,
                        Japan
                    </p>
                </div>
                <hr className="border-b bg-gray-300" />
                <div className="mx-auto w-4/5 reg my-6">
                    <h1 className="text-blue reg text-2xl md:text-3xl md:font-bold mb-2">
                        Gyneocological Conditions
                    </h1>
                    <p className="text-blue mb-7">
                        Ionized water improves body constituents and ensures
                        effective healing to many illnesses. The uses of ionized
                        water in gynecological patients habe proved to be very
                        effective. The main reason for its effectiveness is that
                        this water can neutralize toxins.
                    </p>
                    <p className="text-blue my-7">
                        When given ionized to pre-eclamptic toxemia cases, the
                        results re very significant. During my long years of
                        servicing the pre-eclamptic toxemia cases, I found that
                        the women with pre-eclamptic toxemia who consumed
                        ionized water tend to deliver healthier babies with
                        stronger muscles. A survey report carried out on babies
                        in this group has intelligence above average.
                    </p>
                    <p className="intr text-brown font-medium">
                        - Prof. Watanabe Ifao. Watanabe Hospital, Japan
                    </p>
                </div>
                <hr className="border-b bg-gray-300" />
                <div className="mx-auto w-4/5 reg my-6">
                    <h1 className="text-blue reg text-2xl md:text-3xl md:font-bold mb-2">
                        Diabetes
                    </h1>
                    <p className="text-blue mb-7">
                        When I was serving in the Fire Insurance Association, I
                        used to examine many diabetic patients. Besides treating
                        them with drugs, I provided them with ionized water.
                        After drinking ionized water for one month, 15 diabetic
                        patients were selected and sent to Tokyo University for
                        further test and observations.
                    </p>
                    <p className="text-blue my-7">
                        Initially, the more serious patients were a bit
                        apprehensive about the treatment. When the ionized water
                        was consumed for some time, the sugar in the blood and
                        urine ranged from a ratio of 300 mg/l to 2 mg/ dc. There
                        was a time where the patient had undergone 5 to 6 blood
                        tests a day and detected to be within normal range.
                        Results also showed that even 1 1/2 hour after meals,
                        the blood sugar and urine ratio was 100 mg/dc 0 mg/dc.
                        The sugar in the urine has completely disappeared.
                    </p>
                    <p className="intr text-brown font-medium">
                        - Prof. Kuwata Keijiroo, Doctor of Medicine, Japan
                    </p>
                </div>
            </div>

            <Footer />
        </div>
    );
};

export default Doctors;
