import React from "react";
import Head from "next/head";
import { Footer } from "../components/shared/Footer";
import { Navbar } from "../components/shared/Navbar";

interface ExpertProps {}

const Expert: React.FC<ExpertProps> = ({}) => {
    return (
        <div>
            <Head>
                <title>89 Alkaline - Experts{"'"} opinion</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className="mx-auto max-w-4xl p-7 itc">
                <h1 className="text-center text-blue text-4xl md:text-5xl md:font-bold mb-6">
                    Experts{"'"} opinion
                </h1>
                <div className="w-4/5 mx-auto text-blue reg">
                    <p className="my-7">
                        The individuals quoted bellow have spent their entire
                        lives researching and writing books, articles and
                        publications on detoxifying, well being and bettering
                        one’s lifestyle. They are well known and well respected
                        doctors that have helped countless people from all over
                        the world and all walks of life reach a healthier more
                        vibrant living. These are their words on alkaline water:
                    </p>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIALoAhgMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAFAgMEBgcAAQj/xAA9EAACAQMCBAQDBgUDAwUBAAABAgMABBEFIQYSMUETIlFhcYGRBxQyobHBI0JS0fAVcvEkYuEzQ4KSwhf/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A1h1X0H0psqn9IpUhz3pANAoKvoPpXvKo/lH0pINLzjrQOKq9wKWOXPQfSheqavZ6TaPc306QxL1JO5+A71RdV+1a2AMekWkkhYYWaYELn/aMk/lQaTd3NraRmS5lihj/AKpGCj86EXPFuh22ee9U4/pjY/tWOw3+q6tf/e9VuJmy+3i5VAPYYG3tUnWrywMfJJKrSYxyxzcgFBqEXG+gyDP3hxtnHgscfTNEdP1/Sb8KbO+t5eboA4BPyO9fO80qRvm3mBHvODj6jY0galdBiySlg2xyoz889aD6fBU9qWMegrAeHvtG1TSmCzL95gBAMZc9PbOcfLb2rYuHuI7DiCzFxYS5I2kibZ4z6EUB3y+grjj0FMhs0vNA4AB2pQx6Cm1O1ek0CZ8YGw611JmY8owCd66ggu2TXgNc3WuoPc4oZxLr9roGlSX14dh5Y0HWR+wFE+1Zf9tOocsGnaeAMSM0zH/bgD9TQZ9rOsapxHqDT3UzSE7iNSeSMe3sPWpOlaKb6LyTEyKegUnPwoxwdwVe64gnuWa1059+bHml/wBo9Pc/nWu6PoGmaVAsdnaqMDBd/Mx+JNBm1vo+rTxiOz8M7AHxItvqCaQ/AGu3IHMLeHmO7B2/StjA367UoqKDHP8A+V3YGZ7qJv8AZHj96dH2ZRwpzC4kDjfoCD8u9a1L0qJPgL5wCKDCte4VOnczh+X3bIB+eNvnmg+larf6DqSXdlK8cyHf0ZfQjuK3TULW2uo+WRPiazjizQIoI+aMhI1cEtg4VScE0Fy0D7TLXVmjt2gitrpsALPPyox9iFP54q8WN3cTsVuLGW3I/mLqyt8CDn8q+ar+0WwkaJGLupPmPp1Bx9B6da1L7LuM5LlYdG1Q5dlxazf1Y6off0oNRBpeKbSnloG5MYFdXsw2FdQDm2pKkZpZG9I5d6BXaqJxFwwmr8ZR3d4Q9nb26Axn+Z+YnHwxgn41eugoDby+NcTOT1c/TJA/KgLWqBEVQqgAbAdqlrjFQ4D5dgSafVjQSAfavS23amcnHpXgJJ3P0oFuD3xUK4G2MY9cVKbJ/mxUd4hgkvQDbggHmHpv/wCaAX0K31lPCwA5kI9j7UevowyjflPr61XdQkEAdznrjGelBnHEFqkVyVaQyMuRhRkdd/8AParz9jmnwXNvePOgdrO6V7diPwMVIbHxqm6xqBS7deRSpOfMNznPetE+xqHwdN1IAeX7wuD67UGkLTq00tLU0HSdK6uk6CuoBbNvXobNeMM1w2oFFqrlriKadpCFCyMM/wDyNWE4rOuOLjUU1f7lpto8/iDmABwCTQXi2uYnACSKcehqYjIdxWXroGqSDxb7Vo7FhjMcTE49jjaj2lapNbHwXlFxGm3iIrDA9dxv8qC6E9qSzqgLOwA7k1FEyvGJFbIIyPeqzr+ptIwtIHTLnBZzsKAhqfGWkWEoja7jZz2Q836UNbjO3mQm1USFTuucEiq/bcFWM0hnu7khGyecjHN9akS8PcOwRyRWzQyzYBAaTcZ743oLONVtbpEMUgJbqvQj40C1Fkl5huG7Ef1dqhTaJHZ8jaaeUY5iVfY+uKRHI5bBjbJB8x7UFO1pB95VXAUk4bG/L6mtO+x7xE0u8jY5TxFdT23B/sD86zTiBTFOHxjxBkH8jWs/ZZbSRaG80pLGR+UE9wv/ADQXYU4KbBpYNB7J0FdXjdK6gHMRmkmvCd6SzUDV47x2srxLzOqkgDvVS1FpbqwnvLR5Y7nwyg8fYqTjIz/ariCDQb7qYbmeNt0bDJ8PSgAaNpNiun2z3/3efVBl3klHN1HRcghcDoMY+tEoILS2jEcVuM9GIbY7Yz03O1S0jWPAfbHoOtdcKogZlGM7Cgg3N4bbTH5NhgKtVmxiSTiC0uLty0AbIU9ObpvRziO3b7giL0xk71XbY+LiINnl7570Gj2EkELMZYlEjDlaQZ6eg9B7UL1my0u/EvjI8rO/NzKuWVuUKCDnbAA6U9oly09nGJ1DOBhj60QcZGIk3HQUFM4ds7iwBjujN4fiHkL+Yle2cdKNz6ZHHASQAXJL5+v50XSzEP8AEOC5/EaH67ciGEZ3YkEUGX8VQM2pWsMbYDOEXbvmtHtdVg0y3j07SLWe8FuAJXWTlRGPbJ6nftWV8T3TzakPBkwyuOX4+talwrYmz4dS0JLSrMAxz+Nick5oLdplxNMhE6FSACM9d+1EBUSDqzdugqQDQON0rqQ52rygGnGaSaU3SmzQeiod+eWWFuxyD+VTKiamubfm7qwP7UCQoJ33HbevJ0ixGJiACfyFNwMCfbuaTeQrdQ8nOVZfwnPSggcVmJbEGORckdKzeW5/024ju1cvGXDTKOmO9HuJ9E1vUZI7e3nWKFc5K5yfnQzTOFb2506S1llYEyENNNvyj/tHXNBfoQBbxXNoR4cqhhgbEGitrcjlBb6gdajaTHFaafBbDdI0CDm9tqTOwiU43XBzQT7qQsvkJ9qp3FVxJBYy856AtmjVhec90LeQlmYZB9qqP2jXoVBbrjLg5NBQVVtT1SGGMlTJIF5q3TQrX7pBbW/mJXIjbOcnuT74rF+GLZrriK0SHDOsgblDAE49M9a3bRLO5izNd+TbEcW2V9Scd6AymFUADYbClhqar3PvQOMdq6m2O1dQRG60g16xpJNB6Om/Wm54/Ghkj6FlIB9DSs12QNyaAEkjCUKdgwGc9RtUhpApVdhttmo2oYi1NGQjlcE/P/P1oPqel3ep+LM15NbxoPJFbtgv6kn9qCxCN3QOpG3U96HTSQwyOHbA6mqxHw1eCFls+ILyKKQjnR0U5HyxSLjhye1UtLxJNzkbAJnP1NBY7K+EqKvNhgSuPam7u+eJiX3jyQD7VVdH0m+/1JHi1C4Cq2WL8vLy+4x1NWrULczWzrkenl6UEbT5mTVS/OQojwKqfG87T3zkjARTj40ZspWN83OfPEoXANUriy/El/cxoebzgZHfFAHYypyXMTMjRuOV1OCG6jH0reOAeLU4g09YbllXUIVHir/WP6hWRappJ0vStPtZhi5mzcSr3HYD6fvUrQln024ivLd2jlXBH+elBv8Az13NVd0biG31K2jYSKkxA5kPr7UWWcnvQTS21dUQyEjrXUHrnGSelV7VeI4rSXwoR4jjrvsKc4o1NrOERRHDv39BVFkB5WY5LHfJoD9xxZcD8KItDJOI7+diPGIX/tFDh5lDk/KlJEAWcnYCglWd3KZ/ElZmOcbnNWm3lIjGeh7VSudh5s7fynOM0U0rW1mnNk7EyxpzA46rnH1G1Adl0/xssoX1GabbSuUZSOPOBvtmpdvejw9xuPyr2W8QW5fGT2NAIkcW7NHnzHsB1zUdtQdJQObyd96au3YPJOw2A2wc1X45L7VboRaVaTTE/ic55VOd8ntQLe5NvrN3cN5YxDkknYe/5U9wVwu1zetr2tJ4cQJlhik25R152/YfOrBw9wHJFcfetYuFuHyGECDyAjpnP4v0+NPcdXoht10m03eXe4Yb4Xsp+J/Kgp2pStreuPdhCsTkiPmHRF6be/X51IMTrG6hQQP5QAPmKSi+FGQxOVGNhjffpinuUEr4ThmC+Ye1BHbnjht2iJDmZQcH8Oatmna5PacsdzmUZx7qP3qoz4WWzjjblaSbnJA3HKv/ABR8csgTxWG/4fWgvVrexXEQkicFTXVToHCOUgLLj3xmvKDuI52uLp2PQNgUKZxjHtvmpOpS8wG5HmqHNGrIyuSuRnINByshBH5CmZpcssaKSvr60xElwYwsj5GfxgdRTkv8FlaTCovUjrQezTJEhEhAAGSfSjH2c6cbsy6nMgP3mTlTmH/tL/c1VNQeW9mgtLdeWW7fkXO2Pf5Ctd4btVs7FIVAAiRUXHTAoG7zQLZueWO5ktRy+oKL779vnQeHhvV7jyT3KRorY5wwKuPUbZ+uKoP2o8QXmocQ3GlLM62FtyqIlOBI3KGLH164Hwq7fZNxImo6QmkXT4vLNf4YPWSHOAR8Oh+XrQGrfg2zCgXdzcXC90Dcin6b/nR63s7e1hWG1hSGJRgIi4AqSMDrSXbeggaxfJpli0wAaQ+WNfVv7d6zF2a6d5bhi8zuS7Ywd+tGOJNYa81XljQvFGSkX9LA9Tn3x+VCkw+Xx5sYJL7en9qBlhGObxdlI5twOn0pLgBmVVTnwMDuD614xXxTygMqY5FAyM++/wAaVGGkaTOQynv0O49frQItsnWIlw38O3ZyMj8TMB+gNE18ynlfJ3YYGPhmhunJGNV1FnDAcyLsfwjGf/1RaKNXhblDBM7MwHSgQ5Eo52ZwT3ziup+JZpFzHKAPX1+tdQRLv+NID2zmmXIc8rb5pT8wkYHJHtTBKsSVz6dKBWSoK+UKBgH0oVeOMjI5mG5z7UTuSrJyMDgd8VXtfuvBgMabySH4+wxQFuArZtR1iXU5VzHbgrHnsx61qQZreLlH4igBNVfhTT1sNNs7RMCR8GQ+p6tRzizU/wDRdButRWMySRABF5cjmJCjPtk5oMY+0IqvGOpBAfKI1Px8NajcIrqEnFFiNIkMd2JAEZuyj8WR6YByKH6rfXGoXk19euzXMz5Y+GFBIGPyAXar19jFgZNdurzYpbQcuf8Aub0+hoNktbgTqVI5ZF6rQTijVPu1m0UT8ryAjmzjbviiUipFmVm5FUEls9B3rO9Y1L/VL159xFzckQ9APb17/OgjNyvKjb8qg5IzsfT9aakkdXOVQjAwAds53+e1eXDGGJ1jAlWMjIGw264+VNSTu4V1XC7EbDOdu/yoGp/BTlUHDNlGYHqSNx/nrSvEMivz8sm6hGxtkk/+KhyzxNcI0ynkYFiowDj57Z2pcJRUy0zKoI7ZAAz+3+d6Anw68jR3LbN4lzIMnHby5/KjZXMZUZbfO36UC0F0TTYSqFiQ0hfG+5J/WjKO3hqGkxIN27dulA9b4AIkiyg6eIeufT/O9dURsIg5m2JycrvnevKCPKDGzEbk0w64AKMGz2z3qddqrSEYOBttQ0Dml/8AS/hKN8nG5oESFiZQQOQDfPeg+j2x13iRTj/p7c859sdB9aL6rdJbWEzOMcwKrlcb0vhpI9D4ZbUboETXj+QEeuw/LegvOgxmW7nuCcpGBFGcdfU1QvtQ4qbULptCsTzWkD/9QysB4kg3Az6Lj6j2o5xNxGOHuEoktXEd/egrDnqg/mf5Z+pFY+RlOdkVxzZZlc56nY/H1oPJiwDqDMqs5yHPbYjPv3+lbB9jNt4WlajO3KDLcABVOcAL/cmsbKnPIFfmOPLjqe/51q32U36WWi6o03lC3A5VZs78o70Fr4z1HwrZbCJ8STDmf2XPT5/tVIaZixYERsD5t/K3cj44p+6uJryd7icMs0rZJxkAdh8ht8qiE4m8MMecks2/XagdkjYvuSHbcZ2IPxHxqMw5Il8UqilTHhmA9AOvyqQQ7x8qk+Zjyl8DJ9a63VRH4Uhib15k2Iz+v9zQALqdJZcRsSg8o8/N6/PG1PL4f3dCkqnk6r8CR0NHFsbYq7W6KznmTHbmB/470PutNikiWRbfw1I83KB1PqKDuHLmI2UIOSRleUbYGSOvY1YAzMQ0G4B8ox0XG+fnVbt4ILfl5EMcbnC4yOXcdun/AD7UQ0m4kD3MTMZBHKQjnOSAM4PrQGmkMYJOBv6b15Sop28YjmGCMjy/CuoE3LqZGZTsO1D+dlfMikFiDk9DU24Gw+NRbknxVGeiigHXFm+t6xDYxgiJD4kzdfKK9129OtcUWmk26csFq4GB6/8AH61O4P8Aw60/82w5u+M1XeBiTxVKx3P8Q5NAL4t1P/VtfnZZMQW5+7wKRsEXIz8zk/MUGdDlgYgDnblbpnf32wDTsfmt+Zt25k3PXfmpigdsraW9u47a1t5p5HwscaN5vfG3x+Gc1p0enxaHpMGkwlS7ESXL4/E3qPmANuwoD9lMaHXbhyillgHKSNxllBxRzU3c3965ZiwdAGzuPIaD2UoiMHJVmyuxxj0zioUX8R0dgVVTy/7tjsT6bipV0AsknKAMYxjtuajyeW7kRdk8nlHToKCSeZU8TAXzfi6Aj3+tKaMFEbkAkzyuw6nfc+x6+lMzEmWJSSVKnI7dTTvW7IO4wdv/AK0C0TmZRH5UUYUEb9vavLqF3cyKObGPKeh6dP8AO9T7UAu6kbEjb60x0hGO7N+rUAZ7xIbCaeSIoqAkrggOf3p3RrQ29mnjlQz+eRQd+Y+b/Pah3Em1vaqPwtMQw7HzHrR4Aebb+bNA5dSlFUtHg53zgfD9/wA66o155pkDb+U9flXUH//Z"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            {'"'}Cancer grows in oxygen deprived acidic tissues
                            and disease cannot thrive in an alkaline body.{'"'}
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Otto H. Warburg, D.D.S., M.S</li>
                            <li>Nobel prize winner 1931 in Medicine</li>
                            <li>
                                Author, {"“"}Metabolism of tumors{'"'}
                                (Stoffwechsel der Tumoren)
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts1.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “Ionized alkaline water, has become the most
                            important advancement in health care since Sir
                            Alexander Fleming’s discovery of penicillin.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. William D. Kelly, D.D.S., M.S</li>
                            <li>
                                Administrator of College of Metabolic Medicine
                            </li>
                            <li>Author, “Cancer Cure”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts2.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “International studies show that populations with
                            little or no history of illness, such as cancer…,
                            drink higher (pH) alkaline waters. After all
                            potential risk factors were considered and factored
                            out, it became evident that they had been drinking
                            waters with a pH of 9.0 to 10.0.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Leonard Horowitz, D.M.D., M.A., M.P.H.</li>
                            <li>Author, “Aids and Ebola”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts3.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “Hexagonal (alkaline ionized) water moves easily
                            within the cellular matrix of the body, helping with
                            nutrient absorption and waste removal.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Professor Mu Shik Jhon, M.S, Ph.D.</li>
                            <li>
                                Founding President of the Association of
                                Academies of Sciences in Asia (AASA),
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts4.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “I have had countless numbers of patients with
                            painful osteoarthritis on many different medications
                            for arthritis. Many have been pain free within a
                            couple of months after adjusting their urine pH to
                            7.0 to 7.5 by consuming adequate amounts of alkaline
                            water and alkaline foods. As a result, many are able
                            to go off of their medications.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Don Colbert, M.D.</li>
                            <li>
                                Author “7 Pillars of Health”, “Get Healthy
                                Through Detox and Fasting”
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts5.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “I have administered over 5000 gallons of this water
                            for about every health situation imaginable. I feel
                            that restructured alkaline water can benefit
                            everyone.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>
                                Dr Theodore A. Baroody, M.A., D.C., N.D., Ph.D.,
                                Dipl. Acu.
                            </li>
                            <li>Author “Alkalize or Die”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts6.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “Alkaline water rids the body of acid waste… After
                            carefully evaluating the results of my advice to
                            hundreds of individuals, I’m convinced that toxicity
                            in the form of acidic waste is the primary cause of
                            degenerative disease.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Sherry Rogers, M.D.</li>
                            <li>
                                Fellow of the American College of Allergy and
                                Immunology
                            </li>
                            <li>Author of “Detoxify or Die”, “Pain Free”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts7.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “Drinking four to six glasses of alkaline water a
                            day will help to neutralize over acidity and over
                            time will help to restore your buffering ability.
                            Alkaline water should be used when conditions of
                            over acidity develop, such as cold, flu or
                            bronchitis. Like vitamins C, and Beta Carotene,
                            alkaline water acts as an antioxidant because of its
                            excess supply of free electrons. This can help the
                            body against the development of heart disease,
                            strokes, immune dysfunctions, and other common
                            ailments.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Susan M. Lark, M.D</li>
                            <li>
                                University lecturer at UT Southwestern Medical
                                Center
                            </li>
                            <li>Author of “The Chemistry Of Success”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts8.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “You do not need expensive medicine with all the
                            negative side effects to regain health… Alkaline
                            water has profound long term effects because it
                            alkalizes your body and provides an effective
                            antioxidant.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Ingfreid Hobert M.D., Ph.D.</li>
                            <li>
                                Founder of the “quality circle Ethnomedicine” of
                                the Hannover Medical Association
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts9.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “If someone was to ask me ‘what is the one thing I
                            can do for better health?’ my answer would be to
                            start drinking alkaline ionized water. Even if you
                            are eating acidic foods the most important thing is
                            to start putting in this electron rich alkaline
                            fluid so you can neutralize the acidic foods you are
                            eating.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Robert O. Young, M.S., D.Sc., PhD, N.D</li>
                            <li>
                                Director of Research at the pH Miracle Center,
                                California
                            </li>
                            <li>Author “The pH Miracle” series</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts10.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “After years of very positive continuous clinical
                            experiment that I am conducting with hundreds of
                            clients using electronically restructured alkaline
                            water, it is my opinion that this technology will
                            change the way in which all health providers and the
                            public will approach their health in the coming
                            years….My suggestion is to drink restructured
                            alkaline water whenever possible.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Professor Felicia Drury Climent,</li>
                            <li>Adjunct Professor of City College, New York</li>
                            <li>Author “The Acid-Alkaline Balance Diet</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts11.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “Bad diets such as meat and potatoes, fried foods,
                            soft drink colas, and sugars build up acid salts in
                            the body. Often these deposits, by having to be
                            stored away from the blood flow, can remain in the
                            body for decades. He recommends the consumption of
                            ionized alkaline water, which will slowly and gently
                            wash these salts away.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Hidemitsu Hayashi, M.D.</li>
                            <li>Director of the Water Institute, Tokyo</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts12.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “Increasing your consumption of good quality tap
                            water or filtered water can transform your health
                            and play a central role in the healing of virtually
                            all degenerative diseases. However, alkaline water
                            has profound long-term effects because it alkalizes
                            your body and provides and effective antioxidant.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>David Niven Miller, M.A.</li>
                            <li>Anti-aging expert</li>
                            <li>Author of ‘Grow Youthful’</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts13.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “It is widely recognized in the medical profession
                            that a healthy and clean colon is one of the most
                            important precursors to good health and that the
                            great majority of body ailments and diseases
                            originate in an acidic and dirty colon. Water is
                            essential for your health. Drinking “good water;”
                            especially hard water (rich in minerals) which has
                            much calcium and magnesium keeps your body at an
                            optimal alkaline PH.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Hiromi Shinya, M.D.</li>
                            <li>
                                Director, Shinya Medical Clinic, New York,
                                Clinical Professor of Surgery at Yeshiva
                                University, New York
                            </li>
                            <li>Author of “Enzyme Factor”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts14.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “If the blood develops a more acidic condition, then
                            these excess acidic wastes have to be deposited
                            somewhere in the body. If this unhealthy process
                            continues year after year, …This is the beginning of
                            cancer.” “Modern medicine.. treats these malignant
                            cells as if they were bacteria and viruses, it uses
                            chemotherapy, radiation and surgery to treat cancer.
                            Yet none of these treatments will help very much if
                            the environment of the body continues to remain
                            acidic.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr Keiichi Morishita, M.D., Ph.D.</li>
                            <li>
                                Director of Ochanomizu Clinic, Japan, Head of
                                International Natural Medicine Association
                            </li>
                            <li>Author of “The Hidden Truth of Cancer”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts15.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “The cells and fluids in most people’s bodies…are
                            overly acidic. This can cause a lot of health
                            problems. It prevents your body from neutralizing
                            and disposing of harmful, poisonous toxins and
                            leaves you more susceptible to the cell-damaging
                            free radical oxidation that leads to cancer and
                            other diseases.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Dr. Robert C. Atkins, M.D.</li>
                            <li>
                                Developed the “Atkins Diet”, Noted doctor and
                                cardiologist
                            </li>
                            <li>Author of “Atkins for Life: The Next Level”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts16.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “Here is the simple process of aging. Every living
                            cell within our body creates waste products. … Most
                            of our cells go through metabolism and old dead
                            cells become waste products… These waste products
                            must be discharged from our body… The problem is
                            that, due to several reasons, our body cannot get
                            rid of 100% of the waste products it produces.” “The
                            main reason for this is our lifestyle. We,
                            therefore, spend more time producing waste products
                            than processing them.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Sang Whang, M.Eng.</li>
                            <li>Famed researcher, inventor</li>
                            <li>Author of “Reverse Aging”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts18.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “Alkalize your body and live a healthier, more
                            energized, and ultimately more fulfilling life. Our
                            acid-alkaline balance is a baseline determinant of
                            our physical health.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Tony Robbins</li>
                            <li>
                                Lifestyle Coach – Author of “Awaken the Giant
                                Within”
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts19.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “The most important feature of alkaline water
                            produced by a water ionizer is its oxidation
                            reduction potential (ORP). Water with a high
                            negative ORP is of particular value in its ability
                            to neutralize oxygen free radicals… These electrons
                            are immediately available to engage in reactions
                            that neutralize positively charged free radicals.
                            This is the key benefit of water produced by a water
                            ionizer that is not available by simply drinking
                            water than has had some bicarbonate or other
                            compounds dissolved in it to make it alkaline.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Ray Kurzweil, Ph.D.</li>
                            <li>
                                Inventor, Scientist, Technologist and holder of
                                16 honorary degrees
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts20.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “By drinking alkaline water, the aging process can
                            be reversed and the wastes can be reduced in the
                            long-term to a level of a much younger person. The
                            functions of the organs can be revived.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Harald Tietze</li>
                            <li>Expert on natural herbal medicine</li>
                            <li>Author of “Youthing”</li>
                        </ul>
                    </div>
                </div>
                <div className="mx-auto w-4/5 flex mb-8">
                    <div className="w-1/5 mr-2">
                        <img
                            alt=""
                            className="w-36 h-auto rounded-sm"
                            src="https://kempsingapore.com.sg/wp-content/uploads/2021/12/experts21.jpg"
                        />
                    </div>
                    <div className="w-4/5 ml-2">
                        <p className="text-blue reg">
                            “The hydrating capacity of water can be enhanced by
                            adding a structuring agent. The structuring formula
                            is composed of ionic minerals that organize and
                            reduce the water molecules, holding them together in
                            small clusters, to facilitate their flow through the
                            cell membranes.”
                        </p>
                        <ul className="list-disc intr font-normal ml-5 mt-3">
                            <li>Christopher Vasey, N.D</li>
                            <li>Renowned Naturopath and Researcher</li>
                            <li>Author of “The Water Prescription”</li>
                        </ul>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default Expert;
